# Generated by Django 6.0.4 on 2026-04-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_academics', '0001_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='exam_academics.class')),
            ],
            options={
                'db_table': 'chapters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html_content', models.TextField()),
                ('min_read_time', models.IntegerField(default=60)),
                ('order_index', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(db_column='chapter_id', on_delete=django.db.models.deletion.CASCADE, to='exam_academics.chapter')),
            ],
            options={
                'db_table': 'content',
                'managed': True,
            },
        ),
    ]
