# Generated by Django 6.0.4 on 2026-04-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_quizzes', '0001_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('passing_percentage', models.FloatField(default=40.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quizzes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuizSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, to='exam_quizzes.quiz')),
            ],
            options={
                'db_table': 'quiz_sections',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option', models.IntegerField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='exam_quizzes.quizsection')),
            ],
            options={
                'db_table': 'questions',
                'managed': True,
            },
        ),
    ]
