# Generated by Django 6.0.4 on 2026-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_users', '0001_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clerk_id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('role', models.TextField(choices=[('CENTRAL', 'Central'), ('STATE', 'State'), ('DISTRICT', 'District'), ('INSTITUTION', 'Institution'), ('STUDENT', 'Student')], default='STUDENT')),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('institution_id', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
